<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>03 - amount Value</name>
   <tag></tag>
   <elementGuidId>75f691f6-85ba-4f62-a5e8-2e4e60e372a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'amount', '&quot;', '')])[4]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cm-number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>500</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc-root&quot;)/div[@class=&quot;SignedIn__Page-u96ksb-0 hRXphq&quot;]/div[@class=&quot;SignedIn__StyledPageContent-u96ksb-3 feIxrV&quot;]/div[@class=&quot;SignedIn__Main-u96ksb-2 kqsumZ&quot;]/div[@class=&quot;RoutesCluster___StyledDiv-sc-1v289cb-0 kiFfsB&quot;]/div[@class=&quot;RoutesCluster__ContentWrapper-sc-1v289cb-3 fnBvFg&quot;]/div[@class=&quot;SecondaryNavigation___StyledDiv3-sc-1iy976n-3 bwGhDD&quot;]/div[@class=&quot;SecondaryNavigation___StyledDiv4-sc-1iy976n-4 fsXDuw&quot;]/div[@class=&quot;RoutesTopicManagement__PageContent-g1k35b-0 jfcPDY&quot;]/div[@class=&quot;RoutesTopicManagement__MainContent-g1k35b-1 irojrh&quot;]/div[3]/div[@class=&quot;MessageResults__ResultsWrapper-qos6y8-1 bpTtlt&quot;]/div[@class=&quot;MessageResults__Flexer-qos6y8-0 kMvGLO&quot;]/div[2]/div[1]/div[2]/div[2]/span[1]/div[1]/div[@class=&quot;CardResults__CardResultWrapper-q668dk-0 jEPVcV&quot;]/div[@class=&quot;ReactVirtualized__Grid ReactVirtualized__List CardResults__CardList-q668dk-1 eOpRFG&quot;]/div[@class=&quot;ReactVirtualized__Grid__innerScrollContainer&quot;]/div[1]/div[@class=&quot;CodeWithSidebar__Outer-x035s5-0 iTjpnn CodeWithSidebar-highlight&quot;]/div[@class=&quot;CodeWithSidebar__FlexWrapper-x035s5-2 dUttXd&quot;]/div[@class=&quot;CodeWithSidebar__PanelWrapper-x035s5-1 zkisF&quot;]/div[@class=&quot;CodeWithSidebar__ContentWrapper-x035s5-4 cymZpJ&quot;]/div[@class=&quot;EditorStyle__CodeMirrorTheme-sc-180q9gy-0 kccjXn&quot;]/div[@class=&quot;react-codemirror2&quot;]/div[@class=&quot;CodeMirror cm-s-confluent CodeMirror-wrap CodeMirror-focused&quot;]/div[@class=&quot;CodeMirror-scroll&quot;]/div[@class=&quot;CodeMirror-sizer&quot;]/div[1]/div[@class=&quot;CodeMirror-lines&quot;]/div[1]/div[@class=&quot;CodeMirror-code CodeMirror-crosshair&quot;]/div[88]/pre[@class=&quot;CodeMirror-line&quot;]/span[1]/span[@class=&quot;cm-number&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cc-root']/div/div[7]/div/div/div/div/div[2]/div/div/div[3]/div/div[2]/div[2]/div/div[2]/div[2]/span/div/div[2]/div/div/div/div/div/div/div[3]/div/div/div/div[6]/div/div/div/div/div[5]/div[88]/pre/span/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'amount', '&quot;', '')])[4]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'method', '&quot;', '')])[2]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[88]/pre/span/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
