<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04 - dragAndDropFile</name>
   <tag></tag>
   <elementGuidId>2613063b-cc8c-4e2f-a336-c27726a394ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/div[3]/form/div/div[11]/div/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-bvcb8a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e94ffb8-bd42-4a40-ad46-46e902132ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-bvcb8a</value>
      <webElementGuid>a11b6f82-f58d-44f2-b855-812eb98c9142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96316d3e-eed3-4688-b78e-4c79a564a95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>117adc74-91d1-40ca-870a-bbfbc4c4631c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag and drop your file here, or click to select a fileFormats accepted: .csv</value>
      <webElementGuid>34fd8ee5-be27-471c-b2ce-7891ec3d378c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-725er6&quot;]/div[@class=&quot;MuiBox-root css-h5fkc8&quot;]/div[@class=&quot;MuiBox-root css-bmcixi&quot;]/div[@class=&quot;MuiBox-root css-z3z700&quot;]/form[1]/div[@class=&quot;css-v8ja3r&quot;]/div[11]/div[@class=&quot;MuiBox-root css-i3pbo&quot;]/div[@class=&quot;MuiBox-root css-1isemmb&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-bvcb8a&quot;]</value>
      <webElementGuid>629d1b2e-0e39-4f2e-ad36-05674d77d57d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div[3]/form/div/div[11]/div/div[4]/div/div</value>
      <webElementGuid>908a736b-f6e4-4a4d-93f3-65e32140713b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallets'])[1]/following::div[3]</value>
      <webElementGuid>5e91e11f-1d2c-49cf-9afa-9edc7645fad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[2]/following::div[4]</value>
      <webElementGuid>5670a16d-99d0-482f-b9ee-df0be74ea377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>a6521d44-3896-4607-b216-4792378e4689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drag and drop your file here, or click to select a fileFormats accepted: .csv' or . = 'Drag and drop your file here, or click to select a fileFormats accepted: .csv')]</value>
      <webElementGuid>9e94f475-b5fd-45dc-9d94-ac0ff2cf14b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
