<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confluentUser</name>
   <tag></tag>
   <elementGuidId>30581474-f1a1-4ef9-a31d-6107be971874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email*</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LabeledTextInput__LabeledInput-sc-1vclvcl-0 dcEPUl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;App__RootContainer-e7c1iv-0 fVXtAe&quot;]/div[@class=&quot;App___StyledDiv-e7c1iv-1 uXZjN&quot;]/div[@class=&quot;LandingPageLayout__Wrapper-sc-1l6he3t-0 jZQxNg&quot;]/div[@class=&quot;LandingPageLayout__LeftContentWrapper-sc-1l6he3t-3 cgqPMS&quot;]/div[@class=&quot;Stack-jwqe8h-0 jWoQkR&quot;]/div[@class=&quot;LoginContainer___StyledDiv-sc-17hpcc7-0 fTAYPq&quot;]/form[1]/div[@class=&quot;LoginForm___StyledDiv2-sc-1a2l8uy-3 bKBceh&quot;]/div[@class=&quot;StyleGuide__BaseFieldSet-sc-1ncq81n-22 StyleGuide__FieldSet-sc-1ncq81n-23 knpmji dUZrFS&quot;]/div[@class=&quot;FormItem__Wrapper-sc-1inic75-0 jgqzmW&quot;]/div[1]/div[@class=&quot;Label__LabelContainer-sc-1r3z23s-0 evvAqF&quot;]/input[@class=&quot;LabeledTextInput__LabeledInput-sc-1vclvcl-0 dcEPUl&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div[3]/form/div[2]/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
