<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>09 - Country Value</name>
   <tag></tag>
   <elementGuidId>5b7c9a8f-a733-4840-bb67-ae7b581110e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[contains(@id,'cell')])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dQoVA iuSSGE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Country</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;transactionsListContainer&quot;]/div[@class=&quot;sc-dmlqKv Mkfka&quot;]/div[@class=&quot;sc-fKFxtB gYoRnQ&quot;]/div[@class=&quot;sc-bdfBQB eYemdQ rdt_Table&quot;]/div[@class=&quot;sc-gsTEea gmqPQz rdt_TableHead&quot;]/div[@class=&quot;sc-dlfnuX dxtjMA rdt_TableHeadRow&quot;]/div[@class=&quot;sc-hKgJUU sc-eCstlR sc-iqHYmW dlRliO kmkQtc kHbDpc rdt_TableCol&quot;]/div[@class=&quot;sc-crrszt dTQxWW rdt_TableCol_Sortable&quot;]/div[@class=&quot;sc-dQoVA iuSSGE&quot;]</value>
   </webElementProperties>
</WebElementEntity>
