<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phone</name>
   <tag></tag>
   <elementGuidId>1837a105-602e-41b9-9220-938b2e8ac2a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cc-root&quot;]/div/div[7]/div/div/div/div/div[2]/div/div/div/div/div[3]/div/div[2]/div/div/div[2]/div[2]/span/div/div[2]/div/div/div/div/div/div/div[3]/div/div/div/div[6]/div[1]/div/div/div/div[5]/div[80]/pre/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cm-string</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&quot;+525526904218&quot;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc-root&quot;)/div[@class=&quot;SignedIn__Page-u96ksb-0 cHodPZ&quot;]/div[@class=&quot;SignedIn__StyledPageContent-u96ksb-3 jnrPJW&quot;]/div[@class=&quot;SignedIn__Main-u96ksb-2 bAebqV&quot;]/div[@class=&quot;RoutesCluster___StyledDiv-sc-1v289cb-0 hfYIXi&quot;]/div[@class=&quot;RoutesCluster__ContentWrapper-sc-1v289cb-3 ModIA&quot;]/div[@class=&quot;SecondaryNavigation___StyledDiv4-sc-1iy976n-4 zClZY&quot;]/div[@class=&quot;SecondaryNavigation___StyledDiv5-sc-1iy976n-5 fpASZc&quot;]/div[@class=&quot;SubNavLayout__PageContent-gkwqg5-3 cboUHH&quot;]/div[@class=&quot;SubNavLayout__Wrapper-gkwqg5-0 fabSiE&quot;]/div[@class=&quot;SubNavLayout__LowerContent-gkwqg5-5 bxSim&quot;]/div[@class=&quot;SubNavLayout__GrayScaler-gkwqg5-6 gwKCRW&quot;]/div[3]/div[@class=&quot;MessageResults__ResultsWrapper-qos6y8-1 PrPPy&quot;]/div[@class=&quot;MessageResults__Flexer-qos6y8-0 fpIikG&quot;]/div[2]/div[1]/div[2]/div[2]/span[1]/div[1]/div[@class=&quot;CardResults__CardResultWrapper-q668dk-0 EYkhz&quot;]/div[@class=&quot;ReactVirtualized__Grid ReactVirtualized__List CardResults__CardList-q668dk-1 eZrolG&quot;]/div[@class=&quot;ReactVirtualized__Grid__innerScrollContainer&quot;]/div[1]/div[@class=&quot;CodeWithSidebar__Outer-x035s5-0 gheAHU CodeWithSidebar-highlight&quot;]/div[@class=&quot;CodeWithSidebar__FlexWrapper-x035s5-2 BGklS&quot;]/div[@class=&quot;CodeWithSidebar__PanelWrapper-x035s5-1 fbWwkc&quot;]/div[@class=&quot;CodeWithSidebar__ContentWrapper-x035s5-4 MsISa&quot;]/div[@class=&quot;EditorStyle__CodeMirrorTheme-sc-180q9gy-0 horpam&quot;]/div[@class=&quot;react-codemirror2&quot;]/div[@class=&quot;CodeMirror cm-s-confluent CodeMirror-wrap CodeMirror-focused&quot;]/div[@class=&quot;CodeMirror-scroll&quot;]/div[@class=&quot;CodeMirror-sizer&quot;]/div[1]/div[@class=&quot;CodeMirror-lines&quot;]/div[1]/div[@class=&quot;CodeMirror-code CodeMirror-crosshair&quot;]/div[79]/pre[@class=&quot;CodeMirror-line&quot;]/span[1]/span[@class=&quot;cm-string&quot;]</value>
   </webElementProperties>
</WebElementEntity>
